apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-repcont
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
        tier: front-end
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3