apiVersion: v1
kind: Service
metadata:
  name : myapp-service
spec:
  type: NodePort //ClusterIP or LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 32001 //just in NodePort 
  selector:
    app: myapp
    type: front-end